<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_8178679fcd12d1bf20230623040901642</name>
   <tag></tag>
   <elementGuidId>f131538f-2938-4278-af75-e49650bf063e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='LoanAppBody']/tr[2]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(2) > a[title=&quot;Generate PN&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>183c490f-fa5e-4cf7-bcd0-2b3d0448f157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://lossmetest.cardmri.com:8445/LOSMobileAPI/GetPnAmort/8178679fcd12d1bf20230623040901642</value>
      <webElementGuid>c3fdb3ed-bfc8-47b1-8c3e-88ec1cbe59c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>dab92a28-c8c6-4c39-a188-66a4c630eecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Generate PN</value>
      <webElementGuid>4986b2a7-1b13-40c1-a511-946121a5025a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8178679fcd12d1bf20230623040901642</value>
      <webElementGuid>7ced28a8-7099-488f-b757-4eb7ddd9e5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanAppBody&quot;)/tr[2]/td[2]/a[1]</value>
      <webElementGuid>49314b19-5f7c-41dc-a8c4-40108d7938d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='LoanAppBody']/tr[2]/td[2]/a</value>
      <webElementGuid>4ed25136-8c99-46a8-95d5-929c98111e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'8178679fcd12d1bf20230623040901642')]</value>
      <webElementGuid>f10047ab-db75-4b51-9b70-3a23663f1852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For teller encoding'])[1]/following::a[4]</value>
      <webElementGuid>07f2b47f-8b7f-4b1e-b14c-dab7e5392e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educational Loan College'])[1]/following::a[4]</value>
      <webElementGuid>acc90a86-a2eb-464a-a4b8-914c572a10f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MF Sikap-1'])[1]/preceding::a[1]</value>
      <webElementGuid>30096287-96ba-4d9a-beb5-b6530ba02f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended by Account Officer'])[1]/preceding::a[1]</value>
      <webElementGuid>f184db77-b38e-41cc-8c72-39d4bb5a0069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8178679fcd12d1bf20230623040901642']/parent::*</value>
      <webElementGuid>77e97535-d739-48e4-a9fa-cf2a82a2b914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://lossmetest.cardmri.com:8445/LOSMobileAPI/GetPnAmort/8178679fcd12d1bf20230623040901642')]</value>
      <webElementGuid>596c3b26-a58a-4cea-9b4c-3b8e119412bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>1f0903a3-595c-49a0-b516-a9d6ac00cf56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://lossmetest.cardmri.com:8445/LOSMobileAPI/GetPnAmort/8178679fcd12d1bf20230623040901642' and @title = 'Generate PN' and (text() = '8178679fcd12d1bf20230623040901642' or . = '8178679fcd12d1bf20230623040901642')]</value>
      <webElementGuid>cbbd06ce-3c9a-455d-bbc7-0f6199d87f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
