<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loan Amount Matrix</name>
   <tag></tag>
   <elementGuidId>cf8f7f79-aad8-4119-b0f9-ae4cd48e0b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='access_102']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8bcb5a3-65a8-41b5-a5a0-4bf442a5fd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?panel=LoanAmountMatrix</value>
      <webElementGuid>dec7da2d-9b4d-422e-b6ea-fb0a0c2a3d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>2b497385-6762-4151-a123-5072aa8f7c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan Amount Matrix</value>
      <webElementGuid>9f68de85-e4de-47f5-a503-b751ea97faac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;access_102&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>48080af2-480e-4580-8626-7dc7339dc105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='access_102']/a</value>
      <webElementGuid>80e8e375-7dd8-477e-b0d0-13809dc62f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Matrix'])[1]/following::a[1]</value>
      <webElementGuid>f55efff6-c9c5-4f12-9c92-40a40e31f304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>346b05d7-23b7-44fa-bd0c-8a15a6288284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Product Matrix'])[1]/preceding::a[1]</value>
      <webElementGuid>a8d23d24-63d7-4601-a98d-51520e9e34e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?panel=LoanAmountMatrix')]</value>
      <webElementGuid>27499652-4623-4424-8575-254e07e9c26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>69be5a10-63e5-4fe6-9c10-4c443eb30ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?panel=LoanAmountMatrix' and (text() = 'Loan Amount Matrix' or . = 'Loan Amount Matrix')]</value>
      <webElementGuid>0482867b-3ebe-492d-b8c2-7424d9a2b709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
