<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pro Rate on Half_btnLoadTermModal</name>
   <tag></tag>
   <elementGuidId>7ee8dda3-da8e-4715-ac1a-45be7f1a48b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnLoadTermModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnLoadTermModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d515d7c-74d7-4ff9-b12d-6b0bfecc461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btm-sm btn-bilog btn-primary</value>
      <webElementGuid>2f75d98e-146d-482e-abbb-dd4b903b623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?panel=NewProductMatrix&amp;id=43</value>
      <webElementGuid>213cd002-f18c-49e0-b6d8-e37bd068b7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLoadTermModal</value>
      <webElementGuid>f50d20bc-3c26-4cfb-a772-b8dd9d1fbd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLoadTermModal</value>
      <webElementGuid>c7a83697-37cf-4638-9a1c-4438f7b3f240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit Term</value>
      <webElementGuid>3150d04f-50eb-4874-9312-29c044707d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLoadTermModal&quot;)</value>
      <webElementGuid>568ff691-caab-45e5-80e6-6009ed19d59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnLoadTermModal']</value>
      <webElementGuid>627985c5-37a9-4d15-beb1-f9000eb84265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='LoanTermTable']/tbody/tr/td/a</value>
      <webElementGuid>37a37978-b961-431c-97e8-c36281d9927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro Rate on Half'])[1]/following::a[1]</value>
      <webElementGuid>4ee6fd95-743b-4408-bd53-1fca283fa631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rate'])[1]/following::a[1]</value>
      <webElementGuid>fa320ab3-19ab-4cfb-91f2-8dec6868c61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Product59151'])[1]/preceding::a[1]</value>
      <webElementGuid>01831dae-4c81-4f57-8ba8-638036613e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEEKLY'])[1]/preceding::a[1]</value>
      <webElementGuid>39e65bc9-43b1-4bfa-80b1-6533a8a6f991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?panel=NewProductMatrix&amp;id=43')]</value>
      <webElementGuid>ad23d803-bc90-4eab-9624-0029d9cd8021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>0f13d480-7255-4095-a9fb-debeb24caf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?panel=NewProductMatrix&amp;id=43' and @id = 'btnLoadTermModal' and @name = 'btnLoadTermModal' and @title = 'Edit Term']</value>
      <webElementGuid>29e9e476-a603-495b-95e0-ac6b98dcf0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
