<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Description_btnDeleteMatrix</name>
   <tag></tag>
   <elementGuidId>6741b0c9-1b63-4b17-b69d-28990ff30368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='delMatrix_101,3588,90608,Super Admin,Approval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a92f65df-2087-4b1d-ae2f-ece2bfbe0477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dba8dedf-448f-49c3-990e-a4a189f209fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btm-sm btn-bilog btn-danger btnDeleteMatrix</value>
      <webElementGuid>b05e3401-5e77-4d1d-900d-466253f16d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Row</value>
      <webElementGuid>d98aba95-5b03-4496-8523-b4f7ba69b93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDeleteMatrix</value>
      <webElementGuid>01c100a3-61e2-40db-b49a-bf925d0f53ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delMatrix_101,3588,90608,Super Admin,Approval</value>
      <webElementGuid>d71d8e9e-061e-4654-8f13-7ebc536876f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delMatrix_101,3588,90608,Super Admin,Approval&quot;)</value>
      <webElementGuid>61aa58eb-1a82-4fcc-bc9d-bffaf0f409e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='delMatrix_101,3588,90608,Super Admin,Approval']</value>
      <webElementGuid>8631f4e1-19d6-4965-bf15-988d45859ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable-keytable']/tbody/tr/td/button[2]</value>
      <webElementGuid>eaba5dc0-7243-4574-8061-2ed8cab6c266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::button[2]</value>
      <webElementGuid>d794f9aa-ee56-4dfc-8266-f73305a425a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::button[2]</value>
      <webElementGuid>99581028-6dfe-4c9c-8bfc-15fd3ea2cd6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Admin'])[1]/preceding::button[1]</value>
      <webElementGuid>64e012cf-9208-4842-b748-b7b66b1ba01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval'])[1]/preceding::button[1]</value>
      <webElementGuid>dadb9d4d-71ad-4680-96d2-8cb71dbf17be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b2d379a6-0be0-4465-b187-e6b359751f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Delete Row' and @name = 'btnDeleteMatrix' and @id = 'delMatrix_101,3588,90608,Super Admin,Approval']</value>
      <webElementGuid>20333918-fdb4-4f13-a745-8fd180c6a776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
