<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pro Rate on Half_Test_Product59151</name>
   <tag></tag>
   <elementGuidId>c40569ae-a038-46db-be1b-49ff5f7a5218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='delProduct_43']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delProduct_43</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2cf9fcd-ac6d-46f0-a98e-f19c34be97d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fbbe62c-2ad8-45f5-897f-8418d7592823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btm-sm btn-bilog btn-danger btnDeleteTerm</value>
      <webElementGuid>3f4d24c3-4d10-4caf-8549-c010bd67840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delProduct_43</value>
      <webElementGuid>3725cbf9-3299-40a9-8461-a412386b377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Test_Product59151</value>
      <webElementGuid>b8ab3a70-1070-46e0-aeca-e0e9ce8e8c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Term</value>
      <webElementGuid>806c0cf4-07b4-4c3a-aa34-e5c67540ca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delProduct_43&quot;)</value>
      <webElementGuid>e449921d-e2a8-4dd1-b2f2-4b90455fa224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='delProduct_43']</value>
      <webElementGuid>89205838-4888-45f8-b4d1-97648a04b64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='LoanTermTable']/tbody/tr/td/button</value>
      <webElementGuid>b2ba0b18-f911-4e89-8a6f-8ec1aa57fbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro Rate on Half'])[1]/following::button[1]</value>
      <webElementGuid>855a5026-de57-4868-9a53-86b04b188c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rate'])[1]/following::button[1]</value>
      <webElementGuid>d479c076-dbd6-4ccb-8720-1807a242fc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Product59151'])[1]/preceding::button[1]</value>
      <webElementGuid>d2214205-31cd-4579-8b2f-e91d02f6b978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEEKLY'])[1]/preceding::button[1]</value>
      <webElementGuid>64ece682-a9eb-4bf0-aa05-1209c3ed349d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>de9a5d1b-b435-4510-816d-23530754a159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'delProduct_43' and @name = 'Test_Product59151' and @title = 'Delete Term']</value>
      <webElementGuid>89e9b7c4-be6e-4a9e-b7ee-d4fc0c77e090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
