<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate in PDF</name>
   <tag></tag>
   <elementGuidId>5f70e378-a5e6-457a-a54d-aa89684f3134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnGenerateRSAuditTrailPDF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnGenerateRSAuditTrailPDF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e41d35b8-3105-4dfe-bba6-5cc8fcc4c8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4bf26c6-9229-4403-a29c-5a86bc910f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>fe7c457d-7fcb-4844-928d-8010f94b2519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGenerateRSAuditTrailPDF</value>
      <webElementGuid>364ed8ab-7edb-435d-ac49-36785695f3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate in PDF</value>
      <webElementGuid>957e270c-2c52-4762-84a1-da4dad4ad902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGenerateRSAuditTrailPDF&quot;)</value>
      <webElementGuid>82ea3398-383b-4b2c-b71e-2b34da80ff70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnGenerateRSAuditTrailPDF']</value>
      <webElementGuid>56c9c5c7-9e59-4e7b-ae8e-c9393cf8fb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RSAuditTrail']/div/div/div[2]/div[2]/button</value>
      <webElementGuid>470b45d8-1db9-4969-b4a9-1967aaf33ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[14]/following::button[1]</value>
      <webElementGuid>d4113bee-59ef-4009-b3cc-08d6a53ab9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail Report'])[2]/following::button[2]</value>
      <webElementGuid>4e84f7ca-3b6c-4f77-bc42-d3a9262a5610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate in Excel'])[3]/preceding::button[1]</value>
      <webElementGuid>d656c52a-cf46-42bb-9e45-bfaa9944e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[11]/preceding::button[2]</value>
      <webElementGuid>db46b562-63a0-4802-ad35-b67ed22aba09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div[2]/div[2]/button</value>
      <webElementGuid>a01993f0-f243-418a-9027-a8f35dd329ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnGenerateRSAuditTrailPDF' and (text() = 'Generate in PDF' or . = 'Generate in PDF')]</value>
      <webElementGuid>6cbac3ae-dd88-4cd9-be47-141e569a9a9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
