<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WEEKLY_modeCheck</name>
   <tag></tag>
   <elementGuidId>2213ee90-caf7-40b2-85c3-7c7b7e8ba7b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPayMode_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newPayMode_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f689dda6-12fb-4121-b6a9-92c7cbb93eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae45ef67-24df-40bc-bf2a-e5bc261b07a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modeCheck</value>
      <webElementGuid>9b8210b1-14f0-4eb7-9d36-7a3127ae8ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d9dd044b-0e6f-4863-a586-cf7dabaec76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modeCheck</value>
      <webElementGuid>9949b35c-dc68-4e74-815b-83a90c8b9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPayMode_1</value>
      <webElementGuid>4b31f908-9713-491f-b0ba-6263d013dba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPayMode_1&quot;)</value>
      <webElementGuid>302ad067-4435-4e75-8056-1b71058e5e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPayMode_1']</value>
      <webElementGuid>5cd55f46-c60e-4c3c-b45d-215ee9dcac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='modePaymentPanel']/tr/td/div/label/input</value>
      <webElementGuid>2fbaba72-6b51-452f-ab8c-a1b95e9b8111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/label/input</value>
      <webElementGuid>2d953fb1-1482-4da6-909a-7a72f38912ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'modeCheck' and @id = 'newPayMode_1']</value>
      <webElementGuid>7ee4de48-bc62-4a3a-911d-41f2ded0279b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
