<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Term_txtNewMinAmount_1</name>
   <tag></tag>
   <elementGuidId>6eb912e4-3f9f-4f04-9f56-7e3f661ee5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewMinAmount_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewMinAmount_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60bbc706-67c2-4066-8214-9eaa74da6578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2685406d-c3ab-4067-987b-0ba016aac30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewMinAmount_1</value>
      <webElementGuid>b37ace4f-e6c6-4911-8ae9-f472885159bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_1</value>
      <webElementGuid>92f52613-568d-4bed-ac94-745ed7d488d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Minimum Amount</value>
      <webElementGuid>fee77206-384c-47ac-8d94-2a287f38e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1829b2ff-c930-4cfd-89e6-1bcb39fb8f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewMinAmount_1&quot;)</value>
      <webElementGuid>b9ebcbec-2f61-4608-803b-84c353b1b8f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewMinAmount_1']</value>
      <webElementGuid>35d412ef-acf7-4a58-a08d-d679138ee183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='modePanel_1']/td/div/div[3]/div/div/div/input</value>
      <webElementGuid>9c47c2e3-ca61-43b7-bb15-365d3d66239e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>6089bfc9-f69d-4050-a408-a7461007c748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtNewMinAmount_1' and @placeholder = 'Minimum Amount']</value>
      <webElementGuid>387d48fe-2693-4e62-a25a-b7631c9b188a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
