<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Amount_txtNewMaxAmount_1</name>
   <tag></tag>
   <elementGuidId>4ea5bbe6-1091-493f-b434-28d058393111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewMaxAmount_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewMaxAmount_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a60fddcd-103e-4df5-9dd7-fc90e1625fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>394bba7e-c5b2-4190-a44a-f8297a5c0eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewMaxAmount_1</value>
      <webElementGuid>36e1ce58-906d-458b-ae78-83e67757fa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_1</value>
      <webElementGuid>e9a2c2d9-ad3c-4e69-be28-7422f3578c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maximum Amount</value>
      <webElementGuid>a6f541aa-3807-46fc-af3e-f817d8bc178d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50b379fb-82da-403e-a2cb-fe36a41117a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewMaxAmount_1&quot;)</value>
      <webElementGuid>cfc07658-a4f3-488c-8bda-a3254813042d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewMaxAmount_1']</value>
      <webElementGuid>1ef3650a-003c-46bc-9529-5517e730bedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='modePanel_1']/td/div/div[4]/div/div/div/input</value>
      <webElementGuid>39d56705-b985-4178-b432-68970961a5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[4]/div/div/div/input</value>
      <webElementGuid>d5981217-c8dc-4f55-8a54-b1bd05744c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtNewMaxAmount_1' and @placeholder = 'Maximum Amount']</value>
      <webElementGuid>032a7e26-7399-45d6-b6f9-98623db0dd9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
