<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flat Rate_txtProRate</name>
   <tag></tag>
   <elementGuidId>3c080e7e-5b6c-4195-b8d8-f82c4692caf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtProRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtProRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d1498c7-1360-4701-b3b3-7fef3ddd7d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5c14c159-a397-4bca-9dcf-f810abc0916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProRate</value>
      <webElementGuid>19268be2-ac7a-41d8-8bbc-3749748103a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProRate</value>
      <webElementGuid>4afe991e-a7ff-4bcd-a38f-cf3e4b4a2454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29d4f16a-d3c7-4c84-8f75-0b1b968d6a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pro Rate on Half</value>
      <webElementGuid>4aaf0c03-67aa-4e94-91e8-fdc0abb47102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProRate&quot;)</value>
      <webElementGuid>5f3b9ad2-011e-4d7d-8614-daa845eba7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProRate']</value>
      <webElementGuid>3aa580f2-2a2c-41fa-ba5f-48ab876404ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div/div[5]/div/div/div/input</value>
      <webElementGuid>f3b95d9e-e143-4564-9646-a077d88e1855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>bdf2e9eb-474e-4be6-a657-cfab0c8d4a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtProRate' and @name = 'txtProRate' and @placeholder = 'Pro Rate on Half']</value>
      <webElementGuid>1e2de03d-09e5-48b6-a9ca-ec0624676322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
