<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Amount_txtMaxAmount</name>
   <tag></tag>
   <elementGuidId>fe327214-e21f-4e96-b5ba-462bab8a053e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMaxAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMaxAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bada174b-7a17-401b-9a2e-357751e568d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6e61738d-ab42-418b-95ca-3849e6208e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMaxAmount</value>
      <webElementGuid>c2ccab79-6aca-4fe0-b7e7-f40c2e9b8649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control addMatrix</value>
      <webElementGuid>bdc42054-557b-49b3-be61-e5e0cdfef100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maximum Amount</value>
      <webElementGuid>6aa33ad5-ca1d-471e-b591-8e5cf7808ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77b2fa76-1ca2-43df-9672-90411178a953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMaxAmount&quot;)</value>
      <webElementGuid>59d5de6e-ce2c-4d01-8e3d-97c8770154a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMaxAmount']</value>
      <webElementGuid>13691391-9c8f-4466-974d-f7b1713a4b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewLoanMatrix']/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>c11b542b-f0bd-499f-99c2-01b78a365235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>f72040e9-a2ec-40ee-9c02-073673a8103f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtMaxAmount' and @placeholder = 'Maximum Amount']</value>
      <webElementGuid>a8d3a3b8-7b1a-41b6-89a5-ae0a9713201b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
