<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum Term_txtNewMinAmount_1</name>
   <tag></tag>
   <elementGuidId>6eb912e4-3f9f-4f04-9f56-7e3f661ee5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewMinAmount_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewMinAmount_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2113445f-e64a-43f0-bad6-594055c8db85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2ddfda3c-ca3b-49c5-8eab-da60864a6f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewMinAmount_1</value>
      <webElementGuid>f2d85df9-b117-46ee-81b3-0300eb909cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_1</value>
      <webElementGuid>792576d2-6843-40b2-85ca-ff60b66c265e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Minimum Amount</value>
      <webElementGuid>05626e31-fc11-471d-aff8-357dc8e19f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e81ac998-065e-4b58-be1b-2d98e64064a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewMinAmount_1&quot;)</value>
      <webElementGuid>f479bc8b-ed14-4f36-846e-9590a53aa4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewMinAmount_1']</value>
      <webElementGuid>77746f98-6189-499d-acde-0ddf7635b38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='modePanel_1']/td/div/div[3]/div/div/div/input</value>
      <webElementGuid>b600eb07-5b29-41f9-b08c-2166509f6c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>7a767420-be4f-4160-98c2-5f551554c25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtNewMinAmount_1' and @placeholder = 'Minimum Amount']</value>
      <webElementGuid>faa5b94d-dc02-47cf-8473-ac465e8d81eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
