<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__startDate1</name>
   <tag></tag>
   <elementGuidId>cf7a1bf1-5c39-41f7-8d84-1265e79aa421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startDate1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38751995-659f-40dd-8427-405986186088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02e4193e-f510-4fac-83fd-b96cc00c7a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>e14aaf0f-a74c-4e89-8d2f-161458cc196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate1</value>
      <webElementGuid>20a087d4-4310-4838-b79b-e7f970abe01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Choose Date Start</value>
      <webElementGuid>c7140652-dab5-425a-9ac4-f5d20a827eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate1&quot;)</value>
      <webElementGuid>bb708e01-c215-4f69-98fd-4446b880eb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate1']</value>
      <webElementGuid>eb426998-066e-40db-b0ac-b04f120c37ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RSAuditTrail']/div/div/div[2]/div/div/input</value>
      <webElementGuid>4333d655-2de2-4f33-b2cc-fe45be2d5e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div[2]/div/div/input</value>
      <webElementGuid>4fd0a316-f642-443f-995e-d0c7ce830507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startDate1' and @placeholder = 'Choose Date Start']</value>
      <webElementGuid>ceb7a96c-b1d4-4c6d-baee-521be5b2d629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
