<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Code_txtFlatRate</name>
   <tag></tag>
   <elementGuidId>19537e67-8551-4f30-b7d4-cbb5e4d36d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFlatRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFlatRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f22ecb5-81e0-4bd5-8d29-ca3567e7a9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d4da941d-c923-481a-9726-02728a8e6edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFlatRate</value>
      <webElementGuid>91222f80-3516-4528-9dec-6648df7ec981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFlatRate</value>
      <webElementGuid>7937c851-46d5-4dcb-8130-b22fdeafc86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>90f28c36-0f90-4c19-b483-7852afcedaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Flat Rate</value>
      <webElementGuid>24f2089a-53e3-4d6a-8d6f-701d17f76a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFlatRate&quot;)</value>
      <webElementGuid>5f6e81cf-5074-41ee-b351-c369f18a5a6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFlatRate']</value>
      <webElementGuid>f1207c44-2cd9-4db3-aa49-13f6ecfc7dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>aef04ad7-0d59-45bd-a2bc-863d7d2f20fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>920cd7ed-f6ab-4e18-a255-2024275b2416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtFlatRate' and @name = 'txtFlatRate' and @placeholder = 'Flat Rate']</value>
      <webElementGuid>2a06f19f-12c0-4c71-9803-278f43170e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
