<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Term_txtNewMaxTerm_1</name>
   <tag></tag>
   <elementGuidId>6c118f04-a56e-47ab-948c-ee87f399a176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewMaxTerm_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewMaxTerm_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a60b660-3566-4c48-9dff-50dc0a669ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6a0edeb9-b58c-4fb7-90e4-ec8c5b8067c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewMaxTerm_1</value>
      <webElementGuid>1711a410-fb52-41d2-b594-4483f840cd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_1</value>
      <webElementGuid>8e4b6d25-13c1-4896-a9bb-8e023e46342f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maximum Term</value>
      <webElementGuid>f39b2f47-316b-4f83-9a3d-2b6cecf7f4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a194d3b-7665-449b-b2d8-015c5bdc2598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewMaxTerm_1&quot;)</value>
      <webElementGuid>820403e7-7ec2-413b-bbe1-df5f3e654db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewMaxTerm_1']</value>
      <webElementGuid>ba85155d-6291-4dd9-b27e-aeddb6da5bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='modePanel_1']/td/div/div[2]/div/div/div/input</value>
      <webElementGuid>f531669c-b58a-4f23-a01a-0c6aa0ee09dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div/input</value>
      <webElementGuid>46ab635b-595f-491d-94f5-b2dac998b4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtNewMaxTerm_1' and @placeholder = 'Maximum Term']</value>
      <webElementGuid>8f516009-26cd-4a42-8dd6-c19e32e79499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
