<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Require PPI_chkRequirePPI</name>
   <tag></tag>
   <elementGuidId>826ad5d1-3927-427d-b3df-d3af4972018b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chkRequirePPI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chkRequirePPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7204422c-7b53-4f08-ae8f-74b4c9443c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>974eb7a9-98eb-4d92-9757-fee204ba558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkRequirePPI</value>
      <webElementGuid>bd7a51a8-9b98-439f-bf26-4d82ac38de18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkRequirePPI</value>
      <webElementGuid>ee7d505a-1253-4b2b-bcf5-c2e3f1c974ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8822a94f-580e-4bb8-96f6-71d31ddd1ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chkRequirePPI&quot;)</value>
      <webElementGuid>90437138-671b-4bc1-bd84-c69e1471db1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chkRequirePPI']</value>
      <webElementGuid>09226738-fd83-429b-a333-c1a9b634e384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/div/div/div[6]/div/div/div/div/label/input</value>
      <webElementGuid>2cb3843b-d40b-48d6-bb8e-5f1ae0ca88e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2fcce510-dc33-471e-895a-b2acf3c525cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chkRequirePPI' and @id = 'chkRequirePPI']</value>
      <webElementGuid>16b9db84-d35c-49b6-9578-abec5f04fbf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
