<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Term_txtNewMaxTerm_1</name>
   <tag></tag>
   <elementGuidId>6c118f04-a56e-47ab-948c-ee87f399a176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNewMaxTerm_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNewMaxTerm_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d9aeaa9-9839-45f4-8a7b-534b63e5e10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4292a155-b618-4153-9782-13ed86c33a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNewMaxTerm_1</value>
      <webElementGuid>59da0d02-e45b-4fb6-8672-4afd4ebc95c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form_1</value>
      <webElementGuid>871a5f88-6be7-42be-ae8f-3d74d89a9254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maximum Term</value>
      <webElementGuid>d04f0f8a-bbcf-4817-bebb-420e1fe40aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad42cdeb-5093-4a2d-92e8-7ca4fef2e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNewMaxTerm_1&quot;)</value>
      <webElementGuid>60d4c8d2-2f0c-4e5c-b8b8-a696af0a0c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNewMaxTerm_1']</value>
      <webElementGuid>ed048f36-6a9c-44bb-8c78-c5112d0776c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='modePanel_1']/td/div/div[2]/div/div/div/input</value>
      <webElementGuid>37d4e4b7-35e5-4ff4-9a16-829fc0c541f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div/input</value>
      <webElementGuid>f480612a-05f3-4eac-8c3f-57e36987aff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtNewMaxTerm_1' and @placeholder = 'Maximum Term']</value>
      <webElementGuid>bdd7b867-54e7-48fc-b6be-e2a5d1bf96b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
