<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtMinAmount</name>
   <tag></tag>
   <elementGuidId>daa87cee-f9b8-4560-bcfc-894857dfc032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMinAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMinAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>044d5f11-96d6-4d18-8a30-e0b8ad39ecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4ceb832-c3c8-4b11-8a78-7ad67a5725bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMinAmount</value>
      <webElementGuid>5bb176c0-7a00-4e83-85c5-b9a27007e8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control addMatrix</value>
      <webElementGuid>2a782ddb-1a2f-4c73-86e5-8d810b0be4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Minimum Amount</value>
      <webElementGuid>1c5ae780-7e0b-49ed-b15c-07e7c77bb3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db5ce73c-7da6-4552-b111-f842a24914e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMinAmount&quot;)</value>
      <webElementGuid>5368682c-68ea-4301-9a26-c9145fcd0e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMinAmount']</value>
      <webElementGuid>0a353193-e6da-4cac-8ba5-94715d04975c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewLoanMatrix']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>3e43e415-b687-4476-9632-c186b80eff0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/input</value>
      <webElementGuid>bad1314e-c5dd-4509-9bd0-066c58cb19da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtMinAmount' and @placeholder = 'Minimum Amount']</value>
      <webElementGuid>301e296b-c573-42d9-bf85-e93c17be87b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
