<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Action Recommendation _3b373a</name>
   <tag></tag>
   <elementGuidId>9e9b719d-be99-4227-9444-500a2985f4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f84a9105-8a6b-49f0-a0f2-63dd4ea198c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control addMatrix</value>
      <webElementGuid>03d375f6-8b0a-40dd-8bf5-7d31eddca4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboAction</value>
      <webElementGuid>e037ce58-b0cd-404a-8253-30c4379103a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cboAction</value>
      <webElementGuid>c2107370-78f0-4025-851b-5209ab2fa0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please Select Action Recommendation Approval </value>
      <webElementGuid>4d153b22-bc02-4cfc-b121-8bb18eb4a46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboAction&quot;)</value>
      <webElementGuid>61bda9f0-3659-4763-b246-fea04a424783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboAction']</value>
      <webElementGuid>c74827ec-bc1b-42c1-8388-44806b028a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewLoanMatrix']/div/div/div[2]/div/div[4]/div/select</value>
      <webElementGuid>f219a585-4c0e-457b-b860-e26cf303c422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Amount'])[3]/following::select[2]</value>
      <webElementGuid>f62b750b-d556-4de1-be6a-a5cff69fca6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Amount'])[3]/following::select[2]</value>
      <webElementGuid>418a832c-4332-4cb0-9f6e-c5a7f95606ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[3]/preceding::select[1]</value>
      <webElementGuid>81f52710-4ed5-4e93-bbac-ed39f38c1ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/preceding::select[1]</value>
      <webElementGuid>fd693f54-236b-49cf-b45f-5ca5c55fa049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/select</value>
      <webElementGuid>d261b9f7-e155-473b-ab31-b919da08cde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboAction' and @name = 'cboAction' and (text() = ' Please Select Action Recommendation Approval ' or . = ' Please Select Action Recommendation Approval ')]</value>
      <webElementGuid>d84bcfc3-4374-4d96-9ba4-2aeec071fc4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
