<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Recommendation Approval</name>
   <tag></tag>
   <elementGuidId>c78d7727-488f-47ea-862e-a049a688600e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e51ac509-2174-4bda-976f-53726b1ffc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control updateMatrix</value>
      <webElementGuid>85e8aa25-30cf-441b-b6dd-2fe39c89fb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectAction</value>
      <webElementGuid>e3da9aee-f4b5-443b-a80b-0b24a5ac5c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectAction</value>
      <webElementGuid>4a190358-55e2-48b8-ad3e-951ba9fe62cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recommendation Approval </value>
      <webElementGuid>ab5c1b4d-9bc3-4fb0-82e5-7d9779e33353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectAction&quot;)</value>
      <webElementGuid>e207cc2a-03f4-4d9a-b166-c326a7172e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectAction']</value>
      <webElementGuid>c2352f4f-f327-477b-85e6-504351c5ec83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoanMatrix']/div/div/div[2]/div/form/div[4]/div/select</value>
      <webElementGuid>c15dc8a2-0fc2-4f01-9b98-921168d8bd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Amount'])[2]/following::select[2]</value>
      <webElementGuid>68c1225f-ed81-4c1e-a310-37c0231215ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Amount'])[2]/following::select[2]</value>
      <webElementGuid>f3d95888-373c-498f-9941-980e569bef26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/preceding::select[1]</value>
      <webElementGuid>ed580e6a-625e-497b-9b0b-28e3632fb8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::select[1]</value>
      <webElementGuid>286d1ada-670f-4cd0-916b-a5deec08e883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>c05930cf-8bac-447d-90ca-045769fe0d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectAction' and @name = 'selectAction' and (text() = 'Recommendation Approval ' or . = 'Recommendation Approval ')]</value>
      <webElementGuid>4b42e85d-79d1-491c-8d3f-46c5753ad701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
