<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Action Recommendation _3b373a</name>
   <tag></tag>
   <elementGuidId>9e9b719d-be99-4227-9444-500a2985f4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd1a30cb-5c09-4895-838d-d0d226356ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control addMatrix</value>
      <webElementGuid>75c03b09-60ac-494d-8458-a97326519d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboAction</value>
      <webElementGuid>5b6bc19a-d55c-426c-8a6a-c3d15a072c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cboAction</value>
      <webElementGuid>4bd9a27d-4bc6-4536-9ad3-12d8a559afd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please Select Action Recommendation Approval </value>
      <webElementGuid>46365a32-cdda-401c-b64e-af2b3f31bb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboAction&quot;)</value>
      <webElementGuid>cf163741-ce58-474b-ae20-4f48546e4315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboAction']</value>
      <webElementGuid>09daa27e-83d2-40a4-8c21-bd81fb59bbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewLoanMatrix']/div/div/div[2]/div/div[4]/div/select</value>
      <webElementGuid>296d474e-781f-4fe6-bce8-3892a783244a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Amount'])[3]/following::select[2]</value>
      <webElementGuid>46d8ab33-23c3-4f1b-9b16-77ab2779b19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Amount'])[3]/following::select[2]</value>
      <webElementGuid>e60fee35-1101-48dc-87bc-d8ebe03c1e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[3]/preceding::select[1]</value>
      <webElementGuid>9d2702df-76ba-4c1c-bac4-6c3e3464fa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/preceding::select[1]</value>
      <webElementGuid>b63b931c-cdc3-4772-a88d-1a87e236feaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/select</value>
      <webElementGuid>ee411872-e3d4-4501-803e-67e8ac753c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboAction' and @name = 'cboAction' and (text() = ' Please Select Action Recommendation Approval ' or . = ' Please Select Action Recommendation Approval ')]</value>
      <webElementGuid>baac7c5c-0e26-4ba4-bf47-1ceab5115045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
