<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Loan Amount Matrix</name>
   <tag></tag>
   <elementGuidId>ceb8917a-d263-496c-a2b2-139917f6f0c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='access_102']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72e45a8d-d0ce-4101-baa2-e94e8d080b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan Amount Matrix</value>
      <webElementGuid>0c122de7-9255-45b0-9c82-fd0342b4bc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;access_102&quot;)/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>7ddb23bf-aced-4a48-b384-20e018f83abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='access_102']/a/span</value>
      <webElementGuid>885bc953-fa5b-4254-ba07-2be731ca4f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Matrix'])[1]/following::span[1]</value>
      <webElementGuid>2abb64a2-b119-48c0-9e3d-7c10028e80cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[2]</value>
      <webElementGuid>9b21f5b3-31e2-4e49-ba54-b37043dff794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Product Matrix'])[1]/preceding::span[1]</value>
      <webElementGuid>66fd6922-3916-4e52-ac2b-76b0898d82c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashflow Matrix'])[1]/preceding::span[2]</value>
      <webElementGuid>136e6b45-5b8f-4ccf-bb32-45c106d5c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loan Amount Matrix']/parent::*</value>
      <webElementGuid>cdace416-576c-4151-b5f5-38768d05f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a/span</value>
      <webElementGuid>951927b0-d8fe-4c34-b6a1-b5ad7c98c53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Loan Amount Matrix' or . = 'Loan Amount Matrix')]</value>
      <webElementGuid>2bce18f4-3762-4f0b-94b8-d33fca73a390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
